openapi: 3.0.0
info:
  title: Join Trivia Game API
  version: 1.0.0
  description: API to join a trivia game

paths:
  /test/joingamee:
    post:
      summary: Join a trivia game
      description: Join a trivia game by providing the gameId and teamId in the request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gameId:
                  type: string
                teamId:
                  type: string
              required:
                - gameId
                - teamId
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      x-amazon-apigateway-integration:
        uri: https://9t6aq1p5n9.execute-api.us-east-1.amazonaws.com/test/joingamee
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
