openapi: 3.0.0
info:
  title: Lambda Function API
  version: 1.0.0
paths:
  /create_team:
    post:
      summary: Create a new team with a unique name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        "200":
          description: Team created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  teamId:
                    type: string
                  teamName:
                    type: string
                  adminUserId:
                    type: string
                  allUsers:
                    type: array
                    items:
                      type: object
                      properties:
                        email:
                          type: string
                        name:
                          type: string
                        userId:
                          type: string
        "400":
          description: Bad request - Invalid user ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:189018341439:function:CreateTeam/invocations
        httpMethod: POST
        type: aws_proxy
        credentials: arn:aws:iam::189018341439:user/default
        requestParameters:
          integration.request.header.Access-Control-Allow-Origin: "'*'"
          integration.request.header.Access-Control-Allow-Headers: "'Content-Type'"
          integration.request.header.Access-Control-Allow-Methods: "'GET, POST, OPTIONS'"
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
          required: true
